#!/bin/bash

set -e 

generate_sequence() {
    local len=1050
    local seq=""
    local bases=(A C G T)
    for (( i=0; i<$len; i++ )); do
        seq+=${bases[$RANDOM % 4]}
    done
    echo "$seq"
}

sequence="GCAAGTGACAATTCCTGAGAATAA"
sequence1="TACGACAGCGAATTCCTGAGAATAATTCGAAAATTCGGACCTCGTTCGTCAATAGCTGTCATAAGGTGGGGTTACATCCCGCTCAGTCTATAATAGTGCACTTTTGTGCAGAGATTGCTGAGTGGCGAGAATTACTGTCTGGGAGCTAATGCTCACCGGGTTCAAGTGGACACAACTCGGATCCTAATACGCACATATACCGTAAATTCACGTCAACATCTCGGTATGCGTAGACACAATTGATCAATATCCTGAAAGCCCCGTGATTAAGCTGCGGGGGAATGGCTTATACTCATTAGTGAATAAATACATAGGCGCCAGAGATTATGAACGTTCCTAAGAGTTGGATACCACCATTCAAGGGTTCACGCGCCGGTGTATTCGACTCATCTACGGCCATCAGTGGCGAGTTTACTTACGTGTTAACAGAGTACCGCCCGATTTTCCATGGGGAGTGTATTCAGATGATGCGGGAGACCGGGCAGTAAAATCGCCCCCATCTGAGAATGGCGATCCTTGTGCGTGTCGGTTCGCATTTTTGCTGAGACTAAAAAGACTCCAAAATGTAGATATTATGGTAGCTTGGGTGATGGCCAGTTTACATAGACAGTAAATTAAGTTACTCGAAACCGTACTCATTGTTGTGGAGCCGAC"

a=5
b=2

# echo "Disabling HYPERTREADING for more accurate time estimation"
# sudo sh -c 'echo off > /sys/devices/system/cpu/smt/control'


for i in {1..1} #10
do

    # seqfile=$1
    # Execute the test command with the generated parameters
    echo "./bin/csyncmer \"$sequence\" $a $b"
    ./bin/csyncmer "$sequence" $a $b 0
    # ./bin/syncmer_tree ./bin/csyncmer "$seqfile" $a $b
done
echo "All tests OK."

# echo "Re-enabling HYPERTREADING."
# sudo sh -c 'echo on > /sys/devices/system/cpu/smt/control'